name: Demo workflow
on:
  workflow_dispatch:
    inputs:
      myInput:

jobs:
 build:
  runs-on : ubuntu-latest
  steps: 
    - name: Checkout 
      uses: actions/checkout@v4
    - name: Get the inputs from the user
      run : echo "${{ toJSON(github.event.inputs) }}"
    - name: Run Python      
      run: |
        python demo.py
      
      
      
  

