name: Demo workflow
on:
  push:
  pull_request:
jobs:
 build:
  runs-on : ubuntu-latest
  steps: 
    - name: Checkout 
      uses: actions/checkout@v4
    - name: Print hello      
      run: |
        python demo.py
      
      
      
  

