name: Demo workflow
on:
  workflow_dispatch:
    inputs:
      myInput:
        default: "my input value"


jobs:
 build:
  runs-on : ubuntu-latest
  steps: 
    - name: Checkout 
      uses: actions/checkout@v4
    - name: Get the inputs from the user
      run : echo $myInput
    - name: Run Python      
      run: |
        python demo.py
      
      
      
  

